/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaClasses;

import java.awt.Color;

/**
 *
 * @author user
 */
public class Display_info extends javax.swing.JFrame {

    /**
     * Creates new form Display_info
     */
    public Display_info() {
        initComponents();
    }
    public Display_info(Product data) {
        initComponents();
        txt_ID.setText(Integer.toString(data.getID()));
        txt_price.setText(Integer.toString(data.getPrice()));
        txt_quantity.setText(Integer.toString(data.getQuantity()));
        txt_product.setText(data.getProductName());
        txt_brand.setText(data.getBrand());
        txt_description.setText(data.getDescription());
        txt_category.setText(data.getCategory());
        txt_supplier.setText(data.getSupplier());
        txt_date.setText(data.getDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txt_supplier = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JLabel();
        txt_date = new javax.swing.JLabel();
        txt_product = new javax.swing.JLabel();
        txt_brand = new javax.swing.JLabel();
        txt_price = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JLabel();
        txt_description = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_category = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Information");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 36, 66));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("DATE                       :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 190, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("BRAND                    :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 190, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("UNIT PRICE           :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 190, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("QUANTITY              :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 190, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("DESCRIPTION       :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 190, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("SUPPLIER               :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 190, 40));

        add_button.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        add_button.setForeground(new java.awt.Color(255, 255, 255));
        add_button.setContentAreaFilled(false);
        add_button.setLabel("OK");
        add_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_buttonMouseExited(evt);
            }
        });
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(add_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 130, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("PRODUCT               : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 190, 40));

        txt_supplier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_supplier.setForeground(new java.awt.Color(255, 255, 255));
        txt_supplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(txt_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 230, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("ID                            : ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 190, 40));

        txt_ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_ID.setForeground(new java.awt.Color(255, 255, 255));
        txt_ID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 230, 40));

        txt_date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_date.setForeground(new java.awt.Color(255, 255, 255));
        txt_date.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 230, 40));

        txt_product.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_product.setForeground(new java.awt.Color(255, 255, 255));
        txt_product.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(txt_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 230, 40));

        txt_brand.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_brand.setForeground(new java.awt.Color(255, 255, 255));
        txt_brand.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(txt_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 230, 40));

        txt_price.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_price.setForeground(new java.awt.Color(255, 255, 255));
        txt_price.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 230, 40));

        txt_quantity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_quantity.setForeground(new java.awt.Color(255, 255, 255));
        txt_quantity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(txt_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 230, 40));

        txt_description.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_description.setForeground(new java.awt.Color(255, 255, 255));
        txt_description.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(txt_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 230, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("CATEGORY             :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 190, 40));

        txt_category.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_category.setForeground(new java.awt.Color(255, 255, 255));
        txt_category.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(txt_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 230, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 480, 440));

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Informations");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 40));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Display.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseEntered
        add_button.setForeground(Color.green);
    }//GEN-LAST:event_add_buttonMouseEntered

    private void add_buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseExited
        add_button.setForeground(Color.white);
    }//GEN-LAST:event_add_buttonMouseExited

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        dispose();
    }//GEN-LAST:event_add_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton add_button;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_ID;
    private javax.swing.JLabel txt_brand;
    private javax.swing.JLabel txt_category;
    private javax.swing.JLabel txt_date;
    private javax.swing.JLabel txt_description;
    private javax.swing.JLabel txt_price;
    private javax.swing.JLabel txt_product;
    private javax.swing.JLabel txt_quantity;
    private javax.swing.JLabel txt_supplier;
    // End of variables declaration//GEN-END:variables
}
